---
version: '2'
services:
    db:
        build: ./DB
        ports:
            - 9042:9042

    server:
        build: ./server_java
        expose:
            - 80
        links:
            - db:reto3db

    server-lb:
        image: dockercloud/haproxy
        links:
            - server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8888:80

    tsung:
        build: ./load
        links:
            - server-lb:reto3server
        ports:
            - 10080:80
            - 9999:8091
        environment:
            RATE: 10
            HITS: 10
