version: '2'
services:
  web:
    build: .
    expose:
      - 80

  lb:
    image: dockercloud/haproxy
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - web
    ports:
      - 80:80
      - 70:70
    expose:
      - 80
      - 70

 
